version: '3.5'
services:
  kuber:
    image: datalayer/kuber:0.0.1 
    networks:
      - datalayer
    ports:
      - 9091:9091
    environment:
      APISERVER_HOST: http://localhost:8001
#      KUBER_DATALAYERREST: https://${DLAHOST}
#      KUBER_KUBERREST: https://${DLAHOST}
#      KUBER_KUBERWS: wss://${DLAHOST}
#      KUBER_TWITTERREDIRECT: https://${DLAHOST}/kuber/api/v1/twitter/callback
    volumes:
      - ~/.datalayer:/root/.datalayer
    labels:
      - traefik.frontend.rule=Host:${DLAHOST};PathPrefix:/kuber
      - traefik.port=9091
      - traefik.docker.network=datalayer
