apiVersion: v1
kind: Pod
metadata:
  name: onspecificnode
spec:
  containers:
  - name: dla
    image: datalayer/simpleservice:0.0.1
    ports:
    - containerPort: 9876
  nodeSelector:
    shouldrun: here
