version: '3.5'
services:
  zk:
    image: zookeeper:3.4.13
    container_name: zk
#    hostname: {{.Service.Name}}
    hostname: zk
    networks:
      - datalayer
    restart: always
    ports:
      - 2181:2181
    volumes:
      - zk-logs:/opt/persist/logs
      - zk-data:/opt/persist/data
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
#      ZOO_SERVERS: server.1=zk:2888:3888 server.2=zk-2:2888:3888 server.3=zk-3:2888:3888
      ZOO_LOG_DIR: /opt/persist/logs
      ZOO_DATA_LOG_DIR: /opt/persist/data
    labels:
      - traefik.docker.network=datalayer    
volumes:
  zk-logs:
    name: zk-logs
  zk-data:
    name: zk-data
