version: '3.5'
services:
  ldap:
    image: osixia/openldap:1.2.4
    container_name: ldap
    hostname: ldap.datalayer.io
    domainname: ldap.datalayer.io # important: same as hostname
    networks:
      - datalayer
    environment:
      LDAP_LOG_LEVEL: 256
      LDAP_ORGANISATION: Datalayer Inc.
      LDAP_DOMAIN: datalayer.io
      LDAP_BASE_DN: 
      LDAP_ADMIN_PASSWORD: ${DLA_LDAP_BIND_PWD}
      LDAP_CONFIG_PASSWORD: ${DLA_LDAP_CONFIG_PWD}
      LDAP_READONLY_USER: "false"
      # LDAP_READONLY_USER_USERNAME: readonly
      # LDAP_READONLY_USER_PASSWORD: readonly
      LDAP_RFC2307BIS_SCHEMA: "false"
      LDAP_BACKEND: mdb
      LDAP_TLS: "true"
      LDAP_TLS_CRT_FILENAME: ldap.crt
      LDAP_TLS_KEY_FILENAME: ldap.key
      LDAP_TLS_DH_PARAM_FILENAME: dhparam.pem
      LDAP_TLS_CA_CRT_FILENAME: ca.crt
      LDAP_TLS_ENFORCE: "false"
      LDAP_TLS_CIPHER_SUITE: SECURE256:-VERS-SSL3.0
      LDAP_TLS_PROTOCOL_MIN: 3.5
      LDAP_TLS_VERIFY_CLIENT: try
      LDAP_REPLICATION: "false"
      # LDAP_REPLICATION_CONFIG_SYNCPROV: binddn=cn=admin,cn=config bindmethod=simple credentials=$LDAP_CONFIG_PASSWORD searchbase=cn=config type=refreshAndPersist retry=60 + timeout=1 starttls=critical
      # LDAP_REPLICATION_DB_SYNCPROV: binddn=cn=admin,$LDAP_BASE_DN bindmethod=simple credentials=$LDAP_ADMIN_PASSWORD searchbase=$LDAP_BASE_DN type=refreshAndPersist interval=00:00:00:10 retry=60 + timeout=1 starttls=critical
      # LDAP_REPLICATION_HOSTS: #PYTHON2BASH:['ldap://ldap.example.org','ldap://ldap2.example.org']
      KEEP_EXISTING_CONFIG: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_SSL_HELPER_PREFIX: ldap
    tty: true
    stdin_open: true
    volumes:
      - ldap-lib-data:/var/lib/ldap
      - ldap-slapd-data:/etc/ldap/slapd.d
      - ldap-certs-data:/container/service/slapd/assets/certs/
    ports:
      - 389:389
      - 636:636
    labels:
      - traefik.docker.network=datalayer
volumes:
  ldap-lib-data:
    name: ldap-lib-data
  ldap-slapd-data:
    name: ldap-slapd-data
  ldap-certs-data:
    name: ldap-certs-data
