apiVersion: v1
kind: Pod
metadata:
  name: constraintpod
spec:
  containers:
  - name: dla
    image: datalayer/simpleservice:0.0.1
    ports:
    - containerPort: 9876
    resources:
      limits:
        memory: "64Mi"
        cpu: "500m"
