apiVersion: v1
kind: ReplicationController
metadata:
  name: rcdla
  namespace: other
spec:
  replicas: 2
  selector:
    app: dla
  template:
    metadata:
      name: somename
      labels:
        app: dla
    spec:
      containers:
      - name: dla
        image: datalayer/simpleservice:0.0.1
        ports:
        - containerPort: 9876
