debug = false

logLevel = "ERROR"

defaultEntryPoints = ["https"]

[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
    address = ":443"
    compress = true
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "/certs/letsencrypt/live/datalayer.io/fullchain.pem"
      keyFile = "/certs/letsencrypt/live/datalayer.io/privkey.pem"
      [[entryPoints.https.tls.certificates]]
      certFile = "/certs/letsencrypt/live/www.datalayer.io/fullchain.pem"
      keyFile = "/certs/letsencrypt/live/www.datalayer.io/privkey.pem"
#      [[entryPoints.https.tls.certificates]]
#      certFile = "/certs/letsencrypt/live/ldap.datalayer.io/fullchain.pem"
#      keyFile = "/certs/lletsencrypt/ive/ldap.datalayer.io/privkey.pem"
    [entryPoints.https.redirect]
      regex = "^https://www.datalayer.io/(.*)"
      replacement = "https://datalayer.io/$1"

[retry]

[docker]
  endpoint = "unix:///var/run/docker.sock"
  domain = "datalayer.io"
  watch = true
  exposedByDefault = false

# [acme]
#   email = "info@datalayer.io"
#   storage = "acme.json"
#   entryPoint = "https"
#   onHostRule = true
# [acme.httpChallenge]
#   entryPoint = "http"
# [[acme.domains]]
#   main = "datalayer.io"
# [[acme.domains]]
#  main = "www.datalayer.io"
# [[acme.domains]]
#   main = "ldap.datalayer.io"
# [[acme.domains]]
#   main = "viz.datalayer.io"
