apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-zeppelin
  labels:
    app: {{ template "zeppelin.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "zeppelin.name" . }}
        release: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 0
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: datalayer-role
                operator: In
                values:
                - master
      hostNetwork: {{ .Values.zeppelin.hostNetwork }}
      containers:
        - name: zeppelin
          image: {{ .Values.zeppelin.image }}
          imagePullPolicy: {{ .Values.zeppelin.imagePullPolicy }}
          ports:
            - containerPort: 8080
              name: web
            - containerPort: 4040
              name: spark-ui
          env:
            - name: ZEPPELIN_PORT
              value: "8080"
            - name: SPARK_HOME
              value: "/opt/spark"
            - name: HADOOP_CONF_DIR
              value: "/etc/hdfs/conf"
            - name: ZEPPELIN_CONF_DIR
              value: /opt/zeppelin/notebook/_conf
            - name: ZEPPELIN_NOTEBOOK_REPO
              value: {{ .Values.zeppelin.notebookRepo }}
            - name: ZEPPELIN_INTERPRETER_CONNECT_TIMEOUT
              value: "60000"
#            - name: ZEPPELIN_JAVA_OPTS
#              value: >-
#                -Dspark.driver.memory={{ .Values.spark.driverMemory }}
#                -Dspark.executor.memory={{ .Values.spark.executorMemory }}
#{{- if .Values.hdfs.useConfigMap }}
#            - name: MASTER
#              value: "k8s://https://kubernetes:443"
#            - name: SPARK_SUBMIT_OPTIONS
#              value: >-
#                --deploy-mode client
#                --num-executors {{ .Values.spark.numExecutors }}
#{{- end }}
          volumeMounts:
{{- if .Values.hdfs.useConfigMap }}
            - mountPath: {{ .Values.hdfs.configPath }}
              name: hdfs-config
{{- end }}
          resources:
{{ toYaml .Values.zeppelin.resources | indent 12 }} 
          readinessProbe:
            httpGet:
              path: /zeppelin
              port: 8080
            initialDelaySeconds: 20
            timeoutSeconds: 1
        - name: zeppelin-sidecar
          image: datalayer/k8s-sidecar:1.8.2
          imagePullPolicy: IfNotPresent
          args: ["proxy", "-p", "8001"]
{{- if .Values.hdfs.useConfigMap }}
      volumes:
        - name: hdfs-config
          configMap:
            name: {{ .Values.hdfs.configMapName }}
{{- end }}
