# theme.toml template for a Datalayer theme
# See https://github.com/datalayer/datalayerThemes#themetoml for an example

name = "Datalayer Theme"
license = "MIT"
licenselink = "https://github.com/budparr/gohugo.io/blob/master/LICENSE.md"
description = ""
homepage = "https://github.com/budparr/gohugo.io"
tags = ["website"]
features = ["", ""]
min_version = 0.38

[author]
  name = "Bud Parr"
  homepage = "https://github.com/budparr"
