version: '3.5'
services:
  zoo:
    image: zookeeper:3.4.13
    container_name: zoo
#    hostname: "{{.Service.Name}}"
    hostname: zoo
    networks:
      - solrlab
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - zoo-logs:/opt/persist/logs
      - zoo-data:/opt/persist/data
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_LOG_DIR: /opt/persist/logs
      ZOO_DATA_LOG_DIR: /opt/persist/data
  solr:
    image: solr:7.7.0
    container_name: solr
    restart: always
    networks:
      - solrlab
    ports:
      - 8983:8983
    volumes:
      - solr-logs:/opt/solr/server/logs
      - solr-store:/store/solr
      - solr-docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      SOLR_PORT: 8983
      SOLR_HOME: /opt/solr/server/solr
      SOLR_CONF_DIR: /opt/solr/server/solr
      ZK_HOST: zoo:2181
      SOLR_LOGS_DIR: /opt/solr/server/logs
      SOLR_HOST: solr
      SOLR_HEAP:
      SOLR_JAVA_MEM:
    depends_on:
      - zoo
networks:
  solrlab:
    external: false
    name: solrlab
volumes:
  zoo-logs:
  zoo-data:
  solr-logs:
  solr-store:
  solr-docker-entrypoint-initdb.d:
  solr-data:
