version: '3.5'
services:
  viz:
    image: dockersamples/visualizer
    container_name: viz
    networks:
      - datalayer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 5000:8080
    labels:
      - traefik.frontend.rule=Host:viz.${DLAHOST}
      - traefik.port=8080
      - traefik.docker.network=datalayer
