#!/usr/bin/env bash

# Licensed to Datalayer (https://datalayer.io) under one or more
# contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. Datalayer licenses this file
# to you under the Apache License, Version 2.0 (the 
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# REMOTE_FOLDER|PACKAGE_FILE_NAME|LOCAL_FOLDER

export DISTS="
datalayer-dist|kuber|$DLABIN \
datalayer-dist|hadoop-2.9.2.tar.gz|$DLAOPT \
datalayer-dist|hadoop-3.1.0.tar.gz|$DLAOPT \
datalayer-dist|hbase-2.0.0-bin.tar.gz|$DLAOPT \
datalayer-dist|solr-7.6.0.tgz|$DLAOPT \
datalayer-dist|spark-2.2.0-k8s-0.5.0-bin-hadoop-3.1.0.tgz|$DLAOPT \
datalayer-dist|zookeeper-3.4.12.tar.gz|$DLAOPT \
";
