#!/usr/bin/env bash

# Licensed to Datalayer (https://datalayer.io) under one or more
# contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. Datalayer licenses this file
# to you under the Apache License, Version 2.0 (the 
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

echo -e $BOLD$YELLOW"Pulling Distribution Packages"$NOCOLOR$NOBOLD
echo

source dists

for DIST in $DISTS; do

  REMOTE_FOLDER="$(cut -d'|' -f1 <<<"$DIST")"
  PACKAGE_FILE_NAME="$(cut -d'|' -f2 <<<"$DIST")"
  LOCAL_FOLDER="$(cut -d'|' -f3 <<<"$DIST")"

  REMOTE=s3://$REMOTE_FOLDER/$DLAVERSION/$PACKAGE_FILE_NAME
  LOCAL=$LOCAL_FOLDER/$PACKAGE_FILE_NAME

  echo "Pulling $REMOTE to $LOCAL"
  echo
#  aws s3 cp $REMOTE $LOCAL
  S3_URL=https://$REMOTE_FOLDER.s3.amazonaws.com/$DLAVERSION/$PACKAGE_FILE_NAME
  echo "curl "$S3_URL
  curl -Lo $LOCAL $S3_URL
  if [[ $PACKAGE_FILE_NAME == *gz ]] 
  then
    tar -C $LOCAL_FOLDER -xzf $LOCAL
    rm $LOCAL
  fi
  echo

done
