#!/usr/bin/env bash

# Licensed to Datalayer (https://datalayer.io) under one or more
# contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. Datalayer licenses this file
# to you under the Apache License, Version 2.0 (the 
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

echo -e $YELLOW$BOLD"Installing Docker"$NOBOLD$NOCOLOR
echo

function install_on_linux() {
    if ["${awk -F= '/^NAME/{print $2}' /etc/os-release}" == "Ubuntu"]
    then
        echo
    else
        sudo yum update -y
#        sudo yum install -y yum-utils \
#            device-mapper-persistent-data \
#            lvm2
#        sudo yum-config-manager \
#            --add-repo \
#            https://download.docker.com/linux/centos/docker-ce.repo
#        sudo yum update -y
#        sudo yum install -y docker-ce docker-ce-cli containerd.io
        yum install -y docker
    fi
    sudo systemctl start docker
#    sudo service docker start
#    sudo /etc/init.d/docker start
    sudo docker run hello-world
}

function install_on_macos() {
    echo
}

case "${OS}" in
    LINUX)     install_on_linux;;
    MACOS)     install_on_macos;;
    *)         echo "Unsupported operating system ${OS}"
esac
