#!/usr/bin/env bash

# Licensed to Datalayer (https://datalayer.io) under one or more
# contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. Datalayer licenses this file
# to you under the Apache License, Version 2.0 (the 
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

echo -e $YELLOW$BOLD"Deleting Live Docker Containers..."$NOBOLD$NOCOLOR
echo
docker rm $(docker ps -a -q)
echo

# Just use docker images -a options to know all the images with layers.To know particular layers of particular images you can use docker history $image_name
# Also there is a option to remove dangling images by which you can delete it.
# Dangling images: Docker images consist of multiple layers. Dangling images are layers that have no relationship to any tagged images. They no longer serve a purpose and consume disk space. They can be located by adding the filter flag, -f with a value of dangling=true to the docker images command. When you're sure you want to delete them, you can add the -q flag, then pass their ID to docker rmi:

echo -e $YELLOW$BOLD"Deleting Dangling Docker Images..."$NOBOLD$NOCOLOR
echo
docker rmi $(docker images -f dangling=true -q)
echo

echo -e $YELLOW$BOLD"Deleting Orphaned Docker Images..."$NOBOLD$NOCOLOR
echo
docker rmi -f --no-prune=false $(docker imadoges | awk '/^<none>/ {print $3}')
echo

# echo -e $YELLOW$BOLD"Deleting all images"$NOBOLD$NOCOLOR
# echo
# docker rmi $(docker images -q)
# echo

echo -e $YELLOW$BOLD"Deleting Unused Docker Volumes..."$NOBOLD$NOCOLOR
echo
docker volume prune
echo

