#!/usr/bin/env bash

# Licensed to Datalayer (https://datalayer.io) under one or more
# contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. Datalayer licenses this file
# to you under the Apache License, Version 2.0 (the 
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

echo -e $BOLD$YELLOW"Datalayer Status on Docker Compose"$NOCOLOR$NOBOLD
echo

echo -e $WHITE_BCK"Docker Containers"$NOCOLOR
echo
docker ps
echo

echo -e $WHITE_BCK"Docker Networks"$NOCOLOR
echo
docker network ls
# docker network inspect datalayer_default
echo

echo -e $WHITE_BCK"Docker Volumes"$NOCOLOR
echo
docker volume ls
echo

echo -e $YELLOW"""
open http://localhost/whoami
open http://openldap

open http://localhost:8080/dashboard/

curl -H Host:datalayer.io http://localhost/whoami
dla dsp-local-start --scale whoami=2
for i in {0..20}; do curl -H Host:datalayer.io http://localhost/whoami; sleep 1s; done
"""$NOCOLR
