#!/usr/bin/env bash

# Licensed to Datalayer (https://datalayer.io) under one or more
# contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. Datalayer licenses this file
# to you under the Apache License, Version 2.0 (the 
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

echo -e $BOLD$YELLOW"Starting Datalayer on Docker Swarm"$NOCOLOR$NOBOLD
echo

source dsp-docker

if [ -z "$1" ]; then
  SERVICES=$DOCKER_SERVICES_SWARM
elif [ "$1" == "dev" ]; then
  SERVICES=$DOCKER_SERVICES_SWARM_DEV
elif [ "$1" == "base" ]; then
  SERVICES=$DOCKER_SERVICES_SWARM_BASE
fi

if [ "$1" != "ldap_seed" ] && [ "$1" != "solr_seed" ]; then
  cd $DLAHOME/etc && \
    docker stack deploy \
      $SERVICES \
      datalayer
fi

if [ -z "$1" ]; then
  open http://localhost:8681/?kuberRest=http://localhost:9091
elif [ "$1" == "ldap_seed" ]; then
  ldapadd -x -D $DLA_LDAP_BIND -w $DLA_LDAP_BIND_PWD -H ldap:// -f $DLAHOME/etc/ldap/seed/seed.ldif && \
  ldapsearch -x -D $DLA_LDAP_BIND \
    -w admin -H ldap:// \
    -b "ou=users,dc=datalayer,dc=io" \
    -s sub "(uid=*)"
elif [ "$1" == "solr_seed" ]; then
  $SOLR_HOME/bin/solr create -c datalayer -shards 1 -replicationFactor 1 -d $DLAHOME/etc/solr/conf/datalayer -p 8983 -force
#  $SOLR_HOME/bin/solr zk upconfig -n datalayer -d $DLAHOME/etc/conf/solr -p 8983
  dla solr-help
elif [ "$1" == "seed" ]; then
  open http://localhost:8092/auth/admin
fi
