#!/usr/bin/env bash

# Licensed to Datalayer (https://datalayer.io) under one or more
# contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. Datalayer licenses this file
# to you under the Apache License, Version 2.0 (the 
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

echo -e $BOLD$YELLOW"Datalayer Status on Docker Swarm"$NOCOLOR$NOBOLD
echo

echo -e $WHITE_BCK"Docker Containers"$NOCOLOR
docker ps
echo

echo -e $WHITE_BCK"Docker Stack"$NOCOLOR
docker stack ps datalayer
echo

echo -e $WHITE_BCK"Docker Service"$NOCOLOR
docker service ps datalayer_viz
echo

echo -e $WHITE_BCK"Docker Swarm"$NOCOLOR
echo
docker node ls
docker stack ls
docker stack ps datalayer
docker stack service ls
docker stack services datalayer
docker service ps --no-trunc <service>
echo

echo -e $YELLOW"""
docker stack ps datalayer

docker service ls
docker service ps datalayer_jupyterhub --no-trunc
dla dsp-swarm-logs datalayer_jupyterhub

docker service scale datalayer_zoo=3
docker service ps datalayer_zoo

# traefik
open http://localhost:8089/dashboard/

# whoami
open http://localhost:8076/whoami
open https://${DLAHOST}/whoami
curl -k -H Host:${DLAHOST} https://localhost/whoami
dla dsp-swarm-up --scale whoami=2
for i in {0..20}; do curl -k -H Host:${DLAHOST} https://localhost/whoami; sleep 1s; done

# explorer
open http://localhost:9600
open https://${DLAHOST}

# apis
open http://localhost:8989/api/doc
open https://${DLAHOST}/api/doc

# viz
open http://localhost:5000
open https://viz.${DLAHOST}

# ldap
open http://localhost:8083
open https://ldap.${DLAHOST}

"""$NOCOLOR
