#!/usr/bin/env bash

# Licensed to Datalayer (https://datalayer.io) under one or more
# contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. Datalayer licenses this file
# to you under the Apache License, Version 2.0 (the 
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

DOCKER_VOLUME="
  jupyterhub-data
  jupyterhub-db-data
"

DOCKER_SERVICES_FILE_BASE="
  DLA keycloak/swarm/keycloak.yml
  DLA ldap/swarm/ldap.yml
  DLA ldap-admin/swarm/ldap-admin.yml
  DLA sorl/swarm/solr.yml
  DLA network/swarm/network.yml
  DLA network/swarm/traefik.yml
  DLA whoami/swarm/whoami.yml
  DLA zookeeper/swarm/zookeeper.yml
"

DOCKER_SERVICES_FILE_DEV="
  DLA keycloak/swarm/keycloak.yml
  DLA ldap/swarm/ldap.yml
  DLA ldap-admin/swarm/ldap-admin.yml
  DLA sorl/swarm/solr.yml
  DLA network/swarm/network.yml
  DLA network/swarm/traefik.yml
  DLA zookeeper/swarm/zookeeper.yml
"

DOCKER_SERVICES_FILE="
  DLA apis/swarm/apis.yml
  DLA iam/swarm/iam.yml
  DLA jupyterhub/swarm/jupyterhub.yml
  DLA keycloak/swarm/keycloak.yml
  DLA kuber/swarm/kuber.yml
  DLA library/swarm/library.yml
  DLA ldap/swarm/ldap.yml
  DLA ldap-admin/swarm/ldap-admin.yml
  DLA network/swarm/network.yml
  DLA solr/swarm/solr.yml
  DLA traefik/swarm/traefik.yml
  DLA ui/swarm/ui.yml
  DLA viz/swarm/viz.yml
  DLA whoami/swarm/whoami.yml
  DLA zookeeper/swarm/zookeeper.yml
"

DOCKER_SERVICES_COMPOSE_BASE="${DOCKER_SERVICES_FILE_BASE//DLA/-f}"
DOCKER_SERVICES_SWARM_BASE="${DOCKER_SERVICES_FILE_BASE//DLA/-c}"

DOCKER_SERVICES_COMPOSE_DEV="${DOCKER_SERVICES_FILE_DEV//DLA/-f}"
DOCKER_SERVICES_SWARM_DEV="${DOCKER_SERVICES_FILE_DEV//DLA/-c}"

DOCKER_SERVICES_COMPOSE="${DOCKER_SERVICES_FILE//DLA/-f}"
DOCKER_SERVICES_SWARM="${DOCKER_SERVICES_FILE//DLA/-c}"
