#!/usr/bin/env bash

# Licensed to Datalayer (https://datalayer.io) under one or more
# contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. Datalayer licenses this file
# to you under the Apache License, Version 2.0 (the 
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

declare -a DSP_DOCKER_IMAGES=(
    "datalayer/k8s-sidecar:1.8.2"
    "datalayer/hdfs-base:2.9.0"
    "datalayer/hdfs-nn:2.9.0"
    "datalayer/hdfs-dn:2.9.0"
    "datalayer/spark-base:2.4.0"
    "datalayer/spark:2.4.0"
    "datalayer/spark-py:2.4.0"
    "datalayer/spark-r:2.4.0"
    "datalayer/spark-resource-staging-server:2.2.0"
    "datalayer/spark-shuffle-service:2.2.0"
    "datalayer/spark-init:2.2.0"
    "datalayer/spark-driver:2.2.0"
    "datalayer/spark-driver-py:2.2.0"
    "datalayer/spark-executor:2.2.0"
    "datalayer/spark-executor-py:2.2.0"
    "datalayer/jupyterhub:0.0.1"
    "datalayer/jupyterhub-http-proxy:0.0.1"
    "datalayer/jupyterhub-image-awaiter:0.0.1"
    "datalayer/jupyterhub-network-tools:0.0.1"
    "datalayer/jupyterhub-pod-culler:0.0.1"
    "datalayer/jupyterlab:0.0.1"
  )
