#!/usr/bin/env bash

# Licensed to Datalayer (https://datalayer.io) under one or more
# contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. Datalayer licenses this file
# to you under the Apache License, Version 2.0 (the 
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

restore_ldap_users() {
    echo -e $BOLD$YELLOW"Restore LDAP Users"$NOCOLOR$NOBOLD
    echo
    ldapadd -H ldap:// -x -D "$DLA_LDAP_BIND" -w $DLA_LDAP_BIND_PWD -f ~/backups/users.ldif
}

restore_volumes() {
    echo -e $BOLD$YELLOW"Restore JupyterHub Volumes"$NOCOLOR$NOBOLD
    echo
    docker volume rm -f jupyterhub-data && docker volume create jupyterhub-data
    docker run --rm -v jupyterhub-data:/data -v ~/backups:/backup ubuntu:18.04 bash -c "cd / && tar xvf /backup/jupyterhub-data.tar"
    docker volume rm -f jupyterhub-db-data && docker volume create jupyterhub-db-data
    docker run --rm -v jupyterhub-db-data:/data -v ~/backups:/backup ubuntu:18.04 bash -c "cd / && tar xvf /backup/jupyterhub-db-data.tar"
}

restore_ldap_users
# restore_volumes
