#!/usr/bin/env bash

# Licensed to Datalayer (https://datalayer.io) under one or more
# contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. Datalayer licenses this file
# to you under the Apache License, Version 2.0 (the 
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

echo -e $BOLD$YELLOW"Docker Swarm Init for Datalayer"$NOCOLOR$NOBOLD
echo

# docker network create datalayer

docker swarm init
# docker service create --name registry --publish published=5000,target=5000 registry:2
# curl http://localhost:5000/v2/

echo -e $BOLD$YELLOW"To join a node as manager"$NOCOLOR$NOBOLD
echo
docker swarm join-token manager

echo -e $BOLD$YELLOW"To join a node as worker"$NOCOLOR$NOBOLD
echo
docker swarm join-token worker
