#!/usr/bin/env bash

# Licensed to Datalayer (https://datalayer.io) under one or more
# contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. Datalayer licenses this file
# to you under the Apache License, Version 2.0 (the 
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

echo -e $BOLD$YELLOW"Building Datalayer Docker Images"$NOCOLOR$NOBOLD
echo

# For HDFS Helm Chart.
cd $DLAHOME/etc/k8s-sidecar/docker && \
  ./make build && \
cd $DLAHOME/etc/hdfs-base/docker && \
  ./make build && \
  cd $DLAHOME/etc/hdfs-dn/docker && \
  make build && \
  cd $DLAHOME/etc/hdfs-nn/docker && \
  ./make build && \
# For Spark Helm Chart.
cd $DLAHOME/etc/spark/docker && \
  ./make build && \
# For JupyterHub Helm Chart.
cd $DLAHOME/repos/jupyterhub-proxy-http && \
  git checkout datalayer && \
  docker build -t datalayer/jupyterhub-http-proxy:0.0.1 . && \
cd $DLAHOME/repos/jupyterhub-k8s/images && \
  git checkout datalayer && ./make build && \
cd $DLAHOME/etc/jupyterlab/docker && \
  ./make build
