#!/usr/bin/env bash

# Licensed to Datalayer (https://datalayer.io) under one or more
# contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. Datalayer licenses this file
# to you under the Apache License, Version 2.0 (the 
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

mkdir ~/backups &>/dev/null

backup_ldap_users() {
    echo -e $BOLD$YELLOW"Backup LDAP Users"$NOCOLOR$NOBOLD
    echo
    ldapsearch -x -H ldap:// -b dc=datalayer,dc=io -D "$DLA_LDAP_BIND" -w $DLA_LDAP_BIND_PWD -z 3000 > ~/backups/users.ldif
    ls ~/backups/users.ldif
}

list_volumes() {
    echo -e $BOLD$YELLOW"Backup Docker Volumes"$NOCOLOR$NOBOLD
    echo
    VOLS=$(docker volume ls | awk '// {print $2}' | grep -v VOLUME)
    for VOL in $VOLS
    do
        echo $VOL
    done | sort
}

backup_volumes() {
    echo -e $WHITE_BCK"Backup JupyterHub Volumes"$NOCOLOR
    echo
    docker run --rm -v jupyterhub-data:/data -v ~/backups:/backups ubuntu:18.04 tar cvf /backups/jupyterhub-data.tar /data
    docker run --rm -v jupyterhub-db-data:/data -v ~/backups:/backups ubuntu:18.04 tar cvf /backups/jupyterhub-db-data.tar /data
    echo
    echo -e $WHITE_BCK"Backup LDAP Volumes"$NOCOLOR
    echo
    docker run --rm -v ldap-lib-data:/data -v ~/backups:/backups ubuntu:18.04 tar cvf /backups/ldap-lib-data.tar /data
    docker run --rm -v ldap-slapd-data:/data -v ~/backups:/backups ubuntu:18.04 tar cvf /backups/ldap-slapd-data.tar /data
    docker run --rm -v ldap-certs-data:/data -v ~/backups:/backups ubuntu:18.04 tar cvf /backups/ldap-certs-data.tar /data
    echo
#    echo -e $WHITE_BCK"Backup Solr Volumes"$NOCOLOR
#    echo
#    docker run --rm -v solr_solr-data:/data -v ~/backups:/backups ubuntu:18.04 tar cvf /backups/solr.tar /data
#    echo
#    echo -e $WHITE_BCK"Backup HDFS Namenode Volume"$NOCOLOR
#    echo
#    docker run --rm --volumes-from namenode -v ~/backups:/backups ubuntu:18.04 tar cvf /backups/namenode.tar /hadoop
#    echo
#    echo -e $WHITE_BCK"Backup HDFS Datanodes Volume"$NOCOLOR
#    echo
#    docker run --rm --volumes-from datanode1 -v ~/backups:/backups ubuntu:18.04 tar cvf /backups/datanode1.tar /hadoop
#    echo
}

backup_ldap_users
# list_volumes
# backup_volumes
