#!/usr/bin/env bash

# Licensed to Datalayer (https://datalayer.io) under one or more
# contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. Datalayer licenses this file
# to you under the Apache License, Version 2.0 (the 
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

echo -e $BOLD$YELLOW"DSP LDAP"$NOCOLOR$NOBOLD
echo

echo """
N_DAYS=1 && TIMESTAMP=$(date --date="-$N_DAYS days" +'%Y%m%d'"100000Z")
N_DAYS=1 && TIMESTAMP=$(gdate --date="-$N_DAYS days" +'%Y%m%d'"100000Z") # for mac (with gdate frombrew install coreutils)
ldapsearch -x -H ldap:// -b dc=datalayer,dc=io -D $DLA_LDAP_BIND -w $DLA_LDAP_BIND_PWD "(&(objectclass=inetOrgPerson)(createTimestamp>=$TIMESTAMP))" createTimestamp
ldapsearch -x -H ldap:// -b dc=datalayer,dc=io -D $DLA_LDAP_BIND -w $DLA_LDAP_BIND_PWD "(&(objectclass=inetOrgPerson)(modifyTimestamp>=$TIMESTAMP))" modifyTimestamp
"""

echo -e """
# https://www.surekhatech.com/blog/how-to-add-custom-attribute-entry-for-ldap
cat <<EOF > schema.ldif
dn: cn=schema
changetype: modify
add: attributeTypes
attributeTypes: ( 2.25.128424792425578037463837247958458780603.1
       NAME 'dateOfBirth'
       EQUALITY caseIgnoreMatch
       SUBSTR caseIgnoreSubstringsMatch
       SYNTAX 1.3.6.1.4.1.1466.115.121.1.15 )
attributeTypes: ( 2.25.128424792425578037463837247958458780603.2
       NAME 'gender'
       EQUALITY caseIgnoreMatch
       SUBSTR caseIgnoreSubstringsMatch
       SYNTAX 1.3.6.1.4.1.1466.115.121.1.15{1024} )
-
add: objectClasses
objectClasses: ( 2.25.128424792425578037463837247958458780603.3
   NAME 'samplePerson'
   DESC 'samplePerson'
   SUP inetOrgPerson
   STRUCTURAL
   MAY  (dateOfBirth $ gender)
)
EOF
ldapadd -x -D $DLA_LDAP_BIND -w $DLA_LDAP_BIND_PWD -H ldap:// -f ./schema.ldif
"""
