#!/usr/bin/env bash

# Licensed to Datalayer (https://datalayer.io) under one or more
# contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. Datalayer licenses this file
# to you under the Apache License, Version 2.0 (the 
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

echo -e $BOLD$YELLOW"Apache HBase Help"$NOCOLOR$NOBOLD
echo

echo -e $GREEN$BOLD"HBase Status"$NOBOLD$NOCOLOR
echo
echo -e $BOLD$GREEN"HBase Phoenix"$NOCOLOR$NOBOLD
echo
echo -e "Phoenix CLI                "$YELLOW"dla phoenix-cli"$NOCOLOR
echo
echo -e $GREEN$BOLD"HBase Commands"$NOCOLOR$NOBOLD$NOCOLOR
echo
echo -e "HBase CLI                  "$YELLOW"dla hbase-cli"$NOCOLOR
echo
echo -e $BOLD$GREEN"Command Examples"$NOCOLOR$NOBOLD
echo
echo "  help"
echo "  list"
echo "  create_namespace 'ns'"
echo "  create 'ns:test', 'cf'"
echo "  alter 'ns:test', 'cf2'"
echo "  list 'ns:test'"
echo "  put 'ns:test', 'row1', 'cf:a', 'value1'"
echo "  put 'ns:test', 'row2', 'cf:b', 'value2'"
echo "  put 'ns:test', 'row3', 'cf:c', 'value3'"
echo "  scan 'ns:test'"
echo "  get 'ns:test', 'row1'"
echo "  disable 'ns:test'"
echo "  drop 'ns:test'"
echo "  exit"
echo
echo -e "HMaster WEB Interface      "$YELLOW"http://localhost:16010/master-status"$NOCOLOR
echo -e "RegionServer WEB Interface "$YELLOW"http://localhost:16030/rs-status"$NOCOLOR
echo

# echo -e $GREEN$BOLD""HBase Setup"$NOBOLD$NOCOLOR
# echo
# dla hbase-setup
