#!/usr/bin/env bash

# Licensed to Datalayer (https://datalayer.io) under one or more
# contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. Datalayer licenses this file
# to you under the Apache License, Version 2.0 (the 
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

echo -e $RED"HDFS files will be persisted in folder "$NOCOLOR$RED_BCK"$DLA_HADOOP_DATA_DIR"$NOCOLOR
echo
echo -e $BOLD$RED_BCK"Existing data in that folder will be lost forever!!!"$NOBOLD$NOCOLOR
echo

export DLA_HADOOP_STATUS=init

# read -p "Are you sure you want to remove '$DLA_HADOOP_DATA_DIR' (y/N)?" -n 1 -r

echo -e $YELLOW"Are you sure you want to remove $BOLD'$DLA_HADOOP_DATA_DIR'$NOBOLD (y/N)?"$NOCOLOR
read REPLY

if [[ $REPLY =~ ^[Yy]$ ]]
then

  echo 'Removing all Hadoop files...'
  rm -fr $DLA_HADOOP_DATA_DIR
  mkdir $DLA_HADOOP_DATA_DIR

  echo
  echo All persisted files are removed.
  echo
  echo Formatting Hadoop...
  echo

  $HADOOP_HOME/bin/hdfs namenode -format DatalayerHadoopCluster

  echo
  echo -e $BOLD$GREEN_BCK"HDFS storage is now formatted."$NOCOLOR$NOBOLD

else

  echo
  echo "I have NOT touched the folder... Come back to initialize when you are ready..."

fi

echo
