#!/usr/bin/env bash

# Licensed to Datalayer (https://datalayer.io) under one or more
# contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. Datalayer licenses this file
# to you under the Apache License, Version 2.0 (the 
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

echo -e $BOLD$YELLOW"Kubernetes Help"$NOCOLOR$NOBOLD
echo

echo -e $GREEN$BOLD"Kubernetes Commands"$NOBOLD$NOCOLOR
echo
echo -e "kubectl get nodes"
echo -e "kubectl get deployments"
echo -e "kubectl get pods"
echo -e "kubectl get svc"
echo -e "kubectl get svc --all-namespaces"
echo
echo -e "kubectl proxy"
echo

echo -e $GREEN$BOLD"Kubernetes Status"$NOBOLD$NOCOLOR
echo
echo -e "Kubernetes WEB Interface "$YELLOW"http://localhost:9090"$NOCOLOR" (Default username/password: kubernetes/kubernetes)"
echo
