#!/usr/bin/env bash

# Licensed to Datalayer (https://datalayer.io) under one or more
# contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. Datalayer licenses this file
# to you under the Apache License, Version 2.0 (the 
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

echo -e $BOLD$YELLOW"Kafka Help"$NOCOLOR$NOBOLD
echo

echo -e $GREEN"Define a topic"$NOCOLOR
echo
echo -e "  $KAFKA_HOME/bin/kafka-topics.sh --zookeeper localhost:2181 --create --topic test --replication-factor 1 --partitions 1"
echo
echo -e $GREEN"Produce messages"$NOCOLOR
echo
echo -e "  $KAFKA_HOME/bin/kafka-console-producer.sh --broker-list localhost:9092 --topic test"
echo -e "    This is a message"
echo -e "    This is another message"
echo -e "    ..."
echo -e "    Note: You have to type by yourself the messages via your keyboard..."
echo -e "    Note: For HDP, use port 6667 instead of 9092"
echo
echo -e $GREEN"Consume messages with another process"$NOCOLOR
echo
echo -e "  $KAFKA_HOME/bin/kafka-console-consumer.sh --zookeeper localhost:2181 --topic test --from-beginning"
echo -e "    This is a message"
echo -e "    This is another message"
echo -e "    ..."
echo -e "    Note: The messages you just typed via your keyboard will be shown here..."
echo
