#!/usr/bin/env bash

# Licensed to Datalayer (https://datalayer.io) under one or more
# contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. Datalayer licenses this file
# to you under the Apache License, Version 2.0 (the 
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

echo -e $BOLD$YELLOW"LDAP Help"$NOCOLOR$NOBOLD
echo

echo "Check the following for LDAP status:"
echo
echo "  localhost port 10389"
echo
echo "    admin DN = uid=admin,ou=system"
echo "    password = secret"
echo
echo "    ldapwhoami -h localhost -p 10389 -D \"uid=admin,ou=system\" -w secret"
echo "    ldapmodify -h localhost -p 10389 -D \"uid=admin,ou=system\" -w secret -a -f apache-ds-tutorial.ldif"
echo "    ldapsearch -h localhost -p 10389 -D \"uid=admin,ou=system\" -w secret -b \"o=sevenSeas\" -s sub \"(givenName=William)\" cn"
echo "    ldapsearch -h localhost -p 10389 -b \"o=sevenSeas\" -D \"uid=admin,ou=system\" -w secret \"(objectClass=*)\""
echo "    ldapsearch -h localhost -p 10389 -b \"o=sevenSeas\" -D \"uid=admin,ou=system\" -w secret -s sub \"(cn=James Hook)\" +"
echo
echo "    ldapwhoami -h localhost -p 10389 -D \"cn=Horatio Nelson,ou=people,o=sevenSeas\" -w pass"
echo "    ldapmodify -h localhost -p 10389 -D \"cn=Horatio Nelson,ou=people,o=sevenSeas\" -w pass -a -f captain-hook.ldif"
echo "    ldapmodify -h localhost -p 10389 -D \"cn=Horatio Nelson,ou=people,o=sevenSeas\" -w pass -a -f captain-hook.ldif"
echo "    ldapdelete -h localhost -p 10389 -D \"cn=Horatio Nelson,ou=people,o=sevenSeas\" -w pass -f captain-hook-delete.ldif"
echo
