#!/usr/bin/env bash

# Licensed to Datalayer (https://datalayer.io) under one or more
# contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. Datalayer licenses this file
# to you under the Apache License, Version 2.0 (the 
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

echo -e $BOLD$YELLOW"Stopping Minikube..."$NOCOLOR$NOBOLD
echo

stop_on_linux() {
    minikube stop "$@"
}

stop_on_macos() {
    minikube stop "$@"
}

minikube config set WantReportErrorPrompt false

case "${OS}" in
    LINUX)     stop_on_linux;;
    MACOS)     stop_on_macos;;
    *)         echo "Unsupported operating system ${OS}"
esac

minikube status "$@"
