#!/usr/bin/env bash

# Licensed to Datalayer (https://datalayer.io) under one or more
# contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. Datalayer licenses this file
# to you under the Apache License, Version 2.0 (the 
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

echo -e $BOLD$YELLOW"Minikube Help"$NOCOLOR$NOBOLD
echo

echo -e $GREEN$BOLD"Minikube Commands"$NOBOLD$NOCOLOR
echo
echo -e "minikube logs"
echo -e "minikube logs | grep ServiceClusterIPRange"
echo
echo -e "eval \$(minikube docker-env)"
echo -e "docker ps"
echo
echo -e "kubectl run hello-minikube --image=gcr.io/google_containers/echoserver:1.4 --port=8080"
echo -e "kubectl expose deployment hello-minikube --type=NodePort"
echo -e "curl \$(minikube service hello-minikube --url)"
echo -e "kubectl delete service,deployment hello-minikube"
echo
echo -e "dla minikube-dashboard"
echo -e "kubectl describe rc k8s-dashboard --namespace=kube-system"
echo
minikube help
echo