#!/usr/bin/env bash

# Licensed to Datalayer (https://datalayer.io) under one or more
# contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. Datalayer licenses this file
# to you under the Apache License, Version 2.0 (the 
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

echo -e $BOLD$YELLOW"Deleting Minikube..."$NOCOLOR$NOBOLD
echo

DLA_SKIP_HEADER=true dla minikube-stop
minikube delete || true

delete_on_linux() {
    virsh list
    virsh shutdown minikube || true
    virsh undefine minikube || true
}

delete_on_macos() {
    echo
}

case "${OS}" in
    LINUX)     delete_on_linux;;
    MACOS)     delete_on_macos;;
    *)         echo "Unkown machine ${MACHINE}"
esac

rm -fr ~/.kube
rm -fr ~/.minikube
docker rm -f $(docker ps -a -q) || true

echo

minikube status "$@"
