#!/usr/bin/env bash

# Licensed to Datalayer (https://datalayer.io) under one or more
# contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. Datalayer licenses this file
# to you under the Apache License, Version 2.0 (the 
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

echo -e $BOLD$YELLOW"Installing Zeit Now.sh"$NOCOLOR$NOBOLD
echo

install_on_linux() {
    (rm /usr/local/bin/now* || true) && \
        NOW_VERSION=13.0.0-canary.17 && \
        curl -Lo /usr/local/bin/now-linux.gz https://github.com/zeit/now-cli/releases/download/${NOW_VERSION}/now-linux.gz && \
        gunzip /usr/local/bin/now-linux.gz && \
        mv /usr/local/bin/now-linux /usr/local/bin/now
        chmod +x /usr/local/bin/now
    echo
}

install_on_macos() {
    (rm /usr/local/bin/now* || true) && \
        NOW_VERSION=13.0.0-canary.17 && \
        curl -Lo /usr/local/bin/now-macos.gz https://github.com/zeit/now-cli/releases/download/${NOW_VERSION}/now-macos.gz && \
        gunzip /usr/local/bin/now-macos.gz && \
        mv /usr/local/bin/now-macos /usr/local/bin/now
        chmod +x /usr/local/bin/now
    echo
}

case "${OS}" in
    LINUX)     install_on_linux;;
    MACOS)     install_on_macos;;
    *)         echo "Unsupported operating system ${OS}"
esac
