#!/usr/bin/env bash

# Licensed to Datalayer (https://datalayer.io) under one or more
# contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. Datalayer licenses this file
# to you under the Apache License, Version 2.0 (the 
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# FIX autogen.sh to avoid `Google Test not present.  Fetching gtest-1.5.0 from the web.` failing...
# curl -L https://github.com/google/googletest/archive/release-1.5.0.tar.gz | tar zx
# mv googletest-release-1.5.0 gtest

# PROTOC_VERSION=3.6.1
PROTOC_VERSION=2.5.0

linux_req() {

    echo Linux Requirements.

}

macos_req() {

    echo MacOs Requirements.

    brew install automake
    brew install libtool

}

case "${OS}" in
    LINUX)     linux_req;;
    MACOS)     macos_req;;
    *)         echo "Unsupported operating system ${OS}"
esac

cd $DLAOPT

rm protobuf-$PROTOC_VERSION.tar.gz || true

curl  -Lo protobuf-$PROTOC_VERSION.tar.gz https://github.com/protocolbuffers/protobuf/archive/v$PROTOC_VERSION.tar.gz && \
  tar xvfz protobuf-$PROTOC_VERSION.tar.gz

cd $DLAOPT/protobuf-$PROTOC_VERSION

./autogen.sh && \
  automake && \
  ./configure && \
  make && \
  sudo make install
sudo ldconfig

echo
echo '------------------------'
echo
protoc --version
echo
echo '------------------------'
echo
