#!/usr/bin/env bash

# Licensed to Datalayer (https://datalayer.io) under one or more
# contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. Datalayer licenses this file
# to you under the Apache License, Version 2.0 (the 
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

source $DLASBIN/repos

echo -e $BOLD$YELLOW"Pulling from upstream and Pushing to origin"$NOCOLOR$NOBOLD
echo

for ((i=0; i<${#DLA_REPOS[@]}; i+=4)); do
  echo -e "$GREEN--- pulling and pushing $BOLD${DLA_REPOS[i]}$NOBOLD ---$NOCOLOR"
  cd $DLAHOME/repos/${DLA_REPOS[i]}
  echo -e $YELLOW
  echo -e "name:     ${DLA_REPOS[i]}"
  echo -e "folder:   ${PWD}"
  echo -e "origin:   ${DLA_REPOS[i+1]}"
  echo -e "upstream: ${DLA_REPOS[i+2]}"
  echo -e "branch:   ${DLA_REPOS[i+3]}"
  echo -e $NOCOLOR
  git checkout ${DLA_REPOS[i+3]}
  if [ $? -ne 0 ]
  then
    echo
    echo -e $BOLD$RED"git checkout ${DLA_REPOS[i+3]} failed..."$NOCOLOR$NOBOLD
    echo
    exit -1
  fi
  git pull origin ${DLA_REPOS[i+3]}
  if [ $? -ne 0 ]
  then
    echo
    echo -e $BOLD$RED"git pull origin ${DLA_REPOS[i+3]} failed..."$NOCOLOR$NOBOLD
    echo
    exit -1
  fi
  git fetch upstream
  if [ $? -ne 0 ]
  then
    echo
    echo -e $BOLD$RED"git fetch upstream failed..."$NOCOLOR$NOBOLD
    echo
    exit -1
  fi
  git pull upstream ${DLA_REPOS[i+3]}
  if [ $? -ne 0 ]
  then
    echo
    echo -e $BOLD$RED"git pull upstream ${DLA_REPOS[i+3]} failed..."$NOCOLOR$NOBOLD
    echo
    exit -1
  fi
#  git push origin ${DLA_REPOS[i+3]}
  git push origin ${DLA_REPOS[i+3]} --no-verify
  if [ $? -ne 0 ]
  then
    echo
    echo -e $BOLD$RED"push origin ${DLA_REPOS[i+3]} failed..."$NOCOLOR$NOBOLD
    echo
    exit -1
  fi
  echo
done
