#!/usr/bin/env bash

# Licensed to Datalayer (https://datalayer.io) under one or more
# contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. Datalayer licenses this file
# to you under the Apache License, Version 2.0 (the 
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

echo -e $YELLOW$BOLD"Building Apache Zeppelin"$NOBOLD$NOCOLOR
echo

cd $ZEPPELIN_HOME

export HADOOP_VERSION=2.9.0

# export SPARK_VERSION=2.4.0
# export DLABRANCH=master-spark-k8s-2.4.0

export SPARK_VERSION=2.2.0
export DLABRANCH=datalayer

git checkout $DLABRANCH
echo

./dev/change_scala_version.sh 2.11

rm -fr ./zeppelin-web/src/bower_components && \
  rm -fr ./local-repo && \
  rm -fr ~/.m2/repository/.cache/download-maven-plugin/* && \
  mvn clean

echo

# If you are behind a restricting proxy, ask bower get its dependencies via https (not via git).
# git config --global url."https://".insteadOf git://

# -Phelium-dev \
# -Pexamples \
# -Pr \
# -Phadoop-2.7 \
# -Dspark.src.download.url=file:///$DLAHOME/dist/spark/spark-$SPARK_VERSION.tgz \
# -Dspark.bin.download.url=file:///$DLAHOME/dist/spark/spark-$SPARK_VERSION.tgz \
# -Pspark-2.2 \

mvn install \
  -Pscala-2.11 \
  -Dscala.version=2.11.8 \
  -Dscala.binary.version=2.11 \
  -Dspark.version=$SPARK_VERSION \
  -Dpy4j.version=0.10.7 \
  -Dhadoop-common.version=$HADOOP_VERSION \
  -Dhadoop.version=$HADOOP_VERSION \
  -Dmaven.findbugs.enable=false \
  -Dcheckstyle.skip=true \
  -Denforcer.skip=true \
  -Drat.skip=true \
  -Dcobertura.skip=true \
  -Pbuild-distr \
  -Pvendor-repo \
  -DskipTests \
  -pl '!file,!groovy,!jdbc,!lens,!livy' \
  "$@"

echo
echo -e $BOLD"Apache Zeppelin distribution [$GREEN$(ls $ZEPPELIN_HOME/zeppelin-distribution/target/*.tar.gz)]$NOCOLOR"$NOBOLD
echo
