apiVersion: v1
kind: ReplicationController
metadata:
  name: rcdla
spec:
  replicas: 5
  selector:
    app: dla
  template:
    metadata:
      name: somebadpods
      labels:
        app: dla
    spec:
      containers:
      - name: dla
        image: datalayer/simpleservice:0.0.1
        ports:
        - containerPort: 9876
        env:
        - name: HEALTH_MAX
          value: "3100"
        readinessProbe:
          initialDelaySeconds: 3
          httpGet:
            path: /health
            port: 9876
