apiVersion: v1
kind: Pod
metadata:
  name: ready
spec:
  containers:
  - name: dla
    image: datalayer/simpleservice:0.0.1
    ports:
    - containerPort: 9876
    readinessProbe:
      initialDelaySeconds: 10
      httpGet:
        path: /health
        port: 9876
