{{ if .Values.rbac.enabled -}}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: binderhub
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list", "create", "delete"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: binderhub
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: binderhub
roleRef:
  kind: Role
  name: binderhub
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: binderhub
{{- end }}
