version: '3.5'
services:
  zookeeper:
    image: zookeeper:3.4.13
    container_name: zk
#    hostname: {{.Service.Name}}
    hostname: zk
    networks:
      - datalayer
    restart: always
    ports:
      - 2181:2181
    volumes:
      - zookeeper-logs:/opt/persist/logs
      - zookeeper-data:/opt/persist/data
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
#      ZOO_SERVERS: server.1=zk:2888:3888 server.2=zookeeper-2:2888:3888 server.3=zookeeper-3:2888:3888
      ZOO_LOG_DIR: /opt/persist/logs
      ZOO_DATA_LOG_DIR: /opt/persist/data
    labels:
      - traefik.docker.network=datalayer    
volumes:
  zookeeper-logs:
    name: zookeeper-logs
  zookeeper-data:
    name: zookeeper-data
