apiVersion: v1
kind: Service
metadata:
  name: spark-driver-svc
spec:
  clusterIP: None
  ports:
  - port: 7077
    name: spark-driver-port
  - port: 10000
    name: spark-driver-blockmanager-port
  selector:
    run: spark-pod

