version: "3.5"
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: jupyter/kernel-gateway-nginx
    ports:
      - "8080:80" # for testing proxied access to the kernel gateway from outside docker
    depends_on:
      - kernel_gateway
  kernel_gateway:
    build:
      context: .
      dockerfile: Dockerfile.kg
    image: jupyter/kernel-gateway
    ports:
      - "8888:8888" # for testing direct access to the kernel gateway from outside docker
    environment:
      KG_ALLOW_ORIGIN: '*'
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    environment:
      BASE_GATEWAY_HTTP_URL: http://nginx/jupyter/v1/12345678-1234-1234-1234-123456789012
      BASE_GATEWAY_WS_URL: ws://nginx/jupyter/v1/12345678-1234-1234-1234-123456789012
    depends_on:
      - nginx
