apiVersion: v1
kind: Pod
metadata:
  name: envs
spec:
  containers:
  - name: dla
    image: datalayer/simpleservice:0.0.1
    ports:
    - containerPort: 9876
    env:
    - name: SIMPLE_SERVICE_VERSION
      value: "1.0"
